# GitHub Pages configuration
# Using Jekyll with the Cayman theme for a clean look
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
# Set the title and description shown on the site
# (GitHub Pages automatically infers these from the repository description if not set)
